spring:
  application:
    name: mini_2

  # maria db    
  datasource:
    driver-class-name: ${SPRING_DRIVER}
    url: ${SPRING_URL}
    username: ${SPRING_USERNAME}
    password: ${SPRING_PASSWORD}
    hikari:
      # 15분
      max-lifetime: 1500000   
      # 10
      idle-timeout: 600000 
  
  jpa:
    hibernate:
    # create, create-drop, update, none
      ddl-auto: none
    # 콘솔출력
    show-sql: true
    properties:
      hibernate:
        # mariadb
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  config:
    import: optional:file:.env[.properties]
    
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      
server:
  port: ${SPRING_PORT}
  
jwt:
  secret: ${JWT_SECRET_KEY}
  access-ttl-ms: ${JWT_ACCESS_TTL_MS}
  refresh-ttl-ms: ${JWT_REFRESH_TTL_MS}

openai:
    api-key: ${OPEN_AI_KEY}
    url: ${OPEN_AI_URL}
    model: ${OPEN_AI_MODEL}