spring:
  application:
    name: mini_2

  # maria db    
  datasource:
    driver-class-name: ${SPRING_DRIVER}
    url: ${SPRING_URL}
    username: ${SPRING_USERNAME}
    password: ${SPRING_PASSWORD}
  
  jpa:
    hibernate:
    # create, create-drop, update, none
      ddl-auto: none
    # 콘솔출력
    show-sql: true
    properties:
      hibernate:
        # mariadb
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  config:
    import: optional:file:.env[.properties]
        
server:
  port: ${SPRING_PORT}
  
jwt:
  secret: ${JWT_SECRET_KEY}